[book]
authors = ["Denver Coneyberare"]
language = "en"
multilingual = false
src = "src"
title = "Concurrency Is Hard"

[rust]
edition = "2021"

[build]
extra-watch-dirs = ["po", "third_party"]

[preprocessor.gettext]
after = ["links"]

[preprocessor.svgbob]
renderers = ["html"]
after = ["gettext"]
class = "bob"

[preprocessor.course]
verbose = false # Report timing information.

[output.xgettext]
optional = true
pot-file = "messages.pot"
granularity = 0

[output.pandoc]
optional = true
disabled = true
hosted-html = "https://dconeybe.github.io/concurrency-is-hard"

[output.pandoc.profile.pdf]
output-file = "concurrency-is-hard.pdf"
pdf-engine = "lualatex"

[output.pandoc.profile.pdf.variables]
mainfont = "Noto Serif"
sansfont = "Noto Sans"
monofont = "Noto Sans Mono"
mainfontfallback = [
  "NotoColorEmoji:mode=harf",
  "NotoNaskhArabic:",
]
sansfontfallback = [
  "NotoSansArabic:",
]
monofontfallback = [
  "NotoColorEmoji:mode=harf",
  "NotoSansMath:",
  "NotoSansMonoCJKSC:",
  "NotoSansArabic:",
]
geometry = ["margin=1.25in"]
linkcolor = "blue"
urlcolor = "red"

[output.html]
smart-punctuation = true
additional-js = [
  "theme/speaker-notes.js",
]
additional-css = [
  "theme/css/svgbob.css",
  "theme/css/redbox.css",
  "theme/css/speaker-notes.css",
  "theme/css/language-picker.css",
  "theme/css/rtl.css",
]
site-url = "/concurrency-is-hard/"
git-repository-url = "https://github.com/dconeybe/concurrency-is-hard"
edit-url-template = "https://github.com/dconeybe/concurrency-is-hard/edit/main/{path}"

[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
use-boolean-and = true

# Redirects in the form of "old-path" = "new-path", where the new path
# is relative to the old path.
#
# Please keep the table sorted and avoid multi-step redirects.
[output.html.redirect]

[output.exerciser]
output-directory = "concurrency-is-hard-exercises"

[output.linkcheck]
optional = true
follow-web-links = false # change to true to check web links
exclude = [
  # "crates.io", # uncomment when follow-web-links is true
]
